name: KillKommand
version: 1.0-SNAPSHOT
main: me.gamzer.killkommand.KillKommand
api-version: 1.14
authors: [ Gamzer ]
description: Players can do /suicide to kill themselves
commands:
  kill:
    description: Kills the player to return them to spawn.
    usage: /<command>
    aliases: []